// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGfi_u5vCTjlXRT4t1SzaX6qCRDffPFpc',
    appId: '1:629430804196:web:6172df667b892f277696f1',
    messagingSenderId: '629430804196',
    projectId: 'styx-15067',
    authDomain: 'styx-15067.firebaseapp.com',
    storageBucket: 'styx-15067.appspot.com',
    measurementId: 'G-JHQ8C74YJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKRHZC8xyWTw6rvMIKNvqXCvQNwc8EmgU',
    appId: '1:629430804196:android:8970f48e6f755db87696f1',
    messagingSenderId: '629430804196',
    projectId: 'styx-15067',
    storageBucket: 'styx-15067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmZDjtlcon0jqd8lzXGlaD3Z5sGWO-MYE',
    appId: '1:629430804196:ios:6150703cd96e82e67696f1',
    messagingSenderId: '629430804196',
    projectId: 'styx-15067',
    storageBucket: 'styx-15067.appspot.com',
    iosClientId: '629430804196-e80e0chc89hstm74s2dfcqf4n1ishs56.apps.googleusercontent.com',
    iosBundleId: 'com.example.styx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmZDjtlcon0jqd8lzXGlaD3Z5sGWO-MYE',
    appId: '1:629430804196:ios:6150703cd96e82e67696f1',
    messagingSenderId: '629430804196',
    projectId: 'styx-15067',
    storageBucket: 'styx-15067.appspot.com',
    iosClientId: '629430804196-e80e0chc89hstm74s2dfcqf4n1ishs56.apps.googleusercontent.com',
    iosBundleId: 'com.example.styx',
  );
}
